baseurl = "https://www.prolocobesate.it/"
languageCode = "it"
defaultContentLanguage = "it"
title = "Pro Loco Besate"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
#disqusShortname = "spf13"
# Add your tracking code to enable Google Analytics
googleAnalytics = ""
# Posts per page
paginate = 10

[params]
	author = "Daniele Pala"
	description = "Sito della pro loco di Besate"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = "pro,loco,Besate,proloco"
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/stemma.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	#gravatar = "your@email.com"

	headerText = " "
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = "cover.jpg"
	copyright = "[Daniele Pala](//github.com/danielePala)<br>Realizzato con [Hugo](//gohugo.io/) e [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = "proloco.besate@gmail.com"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = "prolocobesate81"
		flickr = ""
		github = ""
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		gitlab = ""
		trello = ""
